### ISSUE TITLE
DMaS 2nd Room does not split again during Pizza Time

### ISSUE THREAD

**Issue by Vicas** [cccarl/pizza-tower-livesplit-one#2]
![DMaS Room 2](https://user-images.githubusercontent.com/4147318/227548734-9b3f709d-8029-414d-a742-4fd491dfa333.png)

(room picture for reference)

All other revisits split again during Pizza Time so I'm guessing this one just needs to be added to the resplit list

**Comment by cccarl** [comment]
If you mean when exiting this room, yeah that's intended since I also wanted lap 2 splits, so the next split in the list is when you enter the lap 2 portal instead of returning to the first room of the level.

A solution to this is making different routes depending on category, and using the settings to switch between them, but that's gonna be a todo for a distant future. For now simply use the same split for both rooms.
